# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0008_auto_20171026_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='number',
        ),
    ]
